---
abstract: 'installs your dist after releasing'
author:
  - 'Mike Doherty <doherty@cs.dal.ca>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-LocalInstall
requires:
  Carp: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::Plugin: 0
  File::pushd: 0
  Moose: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/doherty/Dist-Zilla-Plugin-LocalInstall/issues
  repository: http://github.com/doherty/Dist-Zilla-Plugin-LocalInstall
version: 0.001
